[project]
name = "CustBuyForecast"
version = "0.1.0"
license = "MIT"
dependencies = [
    "ipykernel>=6.30.1",
    "lightgbm>=4.6.0",
    "matplotlib>=3.10.5",
    "pandas>=2.3.2",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
    "xgboost>=3.0.4",
]
